package com.tedredington.jazzclub.config.file;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.Optional;

import com.tedredington.jazzclub.app.SessionStore;
import com.tedredington.jazzclub.pandora.model.Station;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * pianobar's {@code state} file: volume and last station, written on quit and read on start as
 * settings of the lowest rank, so anything in the config file wins. Same format as the config file.
 */
public final class StateFile implements SessionStore {

    private static final Logger log = LoggerFactory.getLogger(StateFile.class);

    private final Path file;

    public StateFile(Path file) {
        this.file = file;
    }

    @Override
    public void save(int volumeDb, Optional<Station> station) {
        StringBuilder content = new StringBuilder("# do not edit this file\n")
                .append(ConfigKey.VOLUME.fileKey()).append(" = ").append(volumeDb).append('\n');
        station.ifPresent(s ->
                content.append(ConfigKey.AUTOSTART_STATION.fileKey()).append(" = ").append(s.token()).append('\n'));
        try {
            Files.createDirectories(file.getParent());
            // written next to the target and moved into place, so a crash never leaves half a file
            Path temp = Files.createTempFile(file.getParent(), "state", ".tmp");
            Files.writeString(temp, content, StandardCharsets.UTF_8);
            Files.move(temp, file, StandardCopyOption.REPLACE_EXISTING, StandardCopyOption.ATOMIC_MOVE);
        } catch (IOException e) {
            // losing the remembered volume is not worth bothering the user on the way out
            log.debug("Could not write {}", file, e);
        }
    }
}
