package com.tedredington.jazzclub.config.file;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatCode;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Optional;

import com.tedredington.jazzclub.pandora.model.Station;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

class StateFileTest {

    private static final Station EVANS = new Station("139224562502996745", "Bill Evans Radio", true, false, false);

    @TempDir
    Path directory;

    @Test
    void writesPianobarsFormatCreatingTheDirectory() throws IOException {
        Path file = directory.resolve("state/jazzclub/state");

        new StateFile(file).save(-7, Optional.of(EVANS));

        assertThat(Files.readString(file)).isEqualTo("""
                # do not edit this file
                volume = -7
                autostart_station = 139224562502996745
                """);
    }

    @Test
    void whatItWritesIsReadBackByTheConfigParser() {
        Path file = directory.resolve("state");
        new StateFile(file).save(3, Optional.of(EVANS));

        ParsedConfig state = new UserConfigFile().load(file);

        assertThat(state.entries()).containsEntry("volume", "3").containsEntry("autostart_station", EVANS.token());
        assertThat(state.warnings()).isEmpty();
    }

    @Test
    void aStoppedRadioIsRememberedAsNoStationSoTheNextStartAsks() throws IOException {
        Path file = directory.resolve("state");
        new StateFile(file).save(0, Optional.of(EVANS));

        new StateFile(file).save(0, Optional.empty());

        assertThat(Files.readString(file)).doesNotContain("autostart_station");
    }

    @Test
    void noTemporaryFilesAreLeftBehind() throws IOException {
        Path file = directory.resolve("state");
        new StateFile(file).save(1, Optional.empty());
        new StateFile(file).save(2, Optional.empty());

        try (var files = Files.list(directory)) {
            assertThat(files).containsExactly(file);
        }
    }

    @Test
    void anUnwritableLocationIsNotWorthAnErrorOnTheWayOut() throws IOException {
        Path blocker = Files.writeString(directory.resolve("not-a-directory"), "");

        assertThatCode(() -> new StateFile(blocker.resolve("state")).save(0, Optional.empty()))
                .doesNotThrowAnyException();
    }
}
